### ISSUE TITLE
[BUG] Cannot find module 'yup' error introduced in v0.1.0 — missing transitive dependency

### ISSUE THREAD

**Issue by VadenPro1** [JaredCE/serverless-openapi-documenter#273]
After upgrading from 0.0.121 to 0.1.0, the plugin fails at runtime with:

  Error: Cannot find module 'yup'
  Require stack:
  - .../node_modules/@usebruno/schema/src/collections/index.js
  - .../node_modules/@usebruno/schema/src/index.js
  - .../node_modules/@usebruno/converters/dist/cjs/index.js
  - .../node_modules/serverless-openapi-documenter/src/bruno.js
  - .../node_modules/serverless-openapi-documenter/src/collection.js
  - .../node_modules/serverless-openapi-documenter/src/openAPIGenerator.js
  - .../node_modules/serverless-openapi-documenter/index.js

  Steps to Reproduce

  1. Create or use an existing Serverless Framework project with serverless-openapi-documenter configured
  2. Install version 0.1.0:
  yarn add serverless-openapi-documenter@0.1.0
  3. Run any command that loads the plugin (e.g. serverless package, serverless offline, serverless deploy)
  4. Observe the Cannot find module 'yup' error

  You can also reproduce without a full project:
 mkdir repro && cd repro
  echo "nodeLinker: node-modules" > .yarnrc.yml
  yarn init -y
  yarn add serverless-openapi-documenter@0.1.0
  node -e "require('serverless-openapi-documenter')"
  # → Error: Cannot find module 'yup'

  Notes:
  - The nodeLinker: node-modules line is required for yarn v4 to use a traditional node_modules layout (matching yarn v1 and  Lambda deployment environments). Without it, yarn v4's PnP mode intercepts resolution entirely.
  - This does not reproduce with npm install because npm v7+ automatically installs peer dependencies.

  Root Cause

  The 0.1.0 release added Bruno collection support, introducing this dependency chain:

  serverless-openapi-documenter@0.1.0
    └── @usebruno/converters@^0.16.0
          └── @usebruno/schema@0.22.0
                └── yup@^0.32.11  ← declared as peerDependency only

  @usebruno/schema@0.22.0 declares yup as a peerDependency, not a regular dependency. npm/yarn do not auto-install peer
  dependencies, so yup is never present in node_modules unless the end consumer explicitly installs it — which is not
  expected behavior for a plugin dependency.

  Suggested Fix
  1. Add yup as a direct dependency of serverless-openapi-documenter
  2. Update @usebruno/converters to a version that depends on @usebruno/schema@>=0.23.0, where yup was
  https://www.npmjs.com/package/@usebruno/schema?activeTab=versions

  Workaround

  Pin to 0.0.121 until a patch is released.

  Environment

  - serverless-openapi-documenter: 0.1.0
  - @usebruno/converters: 0.16.0
  - @usebruno/schema: 0.22.0
  - Node.js / npm or yarn (reproducible regardless of package manager)

**Comment by JaredCE** [comment]
@VadenPro1 I have updated the @usebruno/converters library and released an update 0.1.1.  It looks like it's back to working as expected for me, can you confirm?

**Comment by VadenPro1** [comment]
Looks good, thanks
